const config = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#ffffff",
        "surface-dim": "#d6dade",
        "surface-bright": "#f6fafe",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f4f8",
        "surface-container": "#eaeef2",
        "surface-container-high": "#e4e9ed",
        "surface-container-highest": "#dfe3e7",
        "on-surface": "#171c1f",
        "on-surface-variant": "#3e4850",
        "inverse-surface": "#2c3134",
        "inverse-on-surface": "#edf1f5",
        outline: "#6e7881",
        "outline-variant": "#bec8d2",
        "surface-tint": "#006591",
        primary: "#006591",
        "on-primary": "#ffffff",
        "primary-container": "#0ea5e9",
        "on-primary-container": "#003751",
        "inverse-primary": "#89ceff",
        secondary: "#006398",
        "on-secondary": "#ffffff",
        "secondary-container": "#5bb8fe",
        "on-secondary-container": "#00476e",
        tertiary: "#396477",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#76a1b6",
        "on-tertiary-container": "#01384a",
        error: "#ea580c",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#c9e6ff",
        "primary-fixed-dim": "#89ceff",
        "on-primary-fixed": "#001e2f",
        "on-primary-fixed-variant": "#004c6e",
        "secondary-fixed": "#cce5ff",
        "secondary-fixed-dim": "#93ccff",
        "on-secondary-fixed": "#001d31",
        "on-secondary-fixed-variant": "#004b73",
        "tertiary-fixed": "#bee9ff",
        "tertiary-fixed-dim": "#a1cde3",
        "on-tertiary-fixed": "#001f2a",
        "on-tertiary-fixed-variant": "#1e4c5f",
        background: "#f6fafe",
        "on-background": "#171c1f",
        "surface-variant": "#dfe3e7",
        "surface-alt": "#f8fafc",
        "text-main": "#0f172a",
        "text-secondary": "#475569",
        "text-muted": "#94a3b8",
        border: "#e2e8f0",
        success: "#10b981",
        warning: "#f59e0b",
        accent: "#6366f1",
      },
      spacing: {
        base: "24px",
        gutter: "16px",
        "sidebar-w": "260px",
        "header-h": "64px",
        "control-h": "40px",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "Arial", "sans-serif"],
        "headline-lg": ["var(--font-inter)", "Inter", "Arial", "sans-serif"],
        "headline-lg-mobile": ["var(--font-inter)", "Inter", "Arial", "sans-serif"],
        "card-title": ["var(--font-inter)", "Inter", "Arial", "sans-serif"],
        "sidebar-item": ["var(--font-inter)", "Inter", "Arial", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "Arial", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "Arial", "sans-serif"],
        "label-bold": ["var(--font-inter)", "Inter", "Arial", "sans-serif"],
        "button-text": ["var(--font-inter)", "Inter", "Arial", "sans-serif"],
      },
      fontSize: {
        "headline-lg": [
          "28px",
          {
            lineHeight: "36px",
            letterSpacing: "0",
            fontWeight: "800",
          },
        ],
        "headline-lg-mobile": [
          "24px",
          {
            lineHeight: "32px",
            fontWeight: "800",
          },
        ],
        "card-title": [
          "17px",
          {
            lineHeight: "24px",
            fontWeight: "700",
          },
        ],
        "sidebar-item": [
          "14px",
          {
            lineHeight: "20px",
            fontWeight: "600",
          },
        ],
        "body-md": [
          "14px",
          {
            lineHeight: "20px",
            fontWeight: "400",
          },
        ],
        "body-sm": [
          "13px",
          {
            lineHeight: "18px",
            fontWeight: "400",
          },
        ],
        "label-bold": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.05em",
            fontWeight: "700",
          },
        ],
        "button-text": [
          "14px",
          {
            lineHeight: "20px",
            fontWeight: "600",
          },
        ],
      },
      boxShadow: {
        "admin-card": "0 1px 4px rgba(0, 0, 0, 0.05)",
      },
    },
  },
};

module.exports = config;
