CREATE TABLE IF NOT EXISTS `Account` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`email` VARCHAR(255) NOT NULL,
	`passwordHash` VARCHAR(255) NOT NULL,
	`fullName` VARCHAR(255) NOT NULL,
	`phone` VARCHAR(20) NOT NULL,
	`role` VARCHAR(20) NOT NULL DEFAULT 'CUSTOMER',
	`status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
	`createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `UserToken` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`userId` INTEGER NOT NULL,
	`refreshToken` VARCHAR(500) NOT NULL,
	`expiresAt` DATETIME NOT NULL,
	`createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `UserAddress` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`userId` INTEGER NOT NULL,
	`recipientName` VARCHAR(255) NOT NULL,
	`phone` VARCHAR(20) NOT NULL,
	`addressLine` TEXT NOT NULL,
	`city` VARCHAR(100) NOT NULL,
	`district` VARCHAR(100) NOT NULL,
	`ward` VARCHAR(100) NOT NULL,
	`isDefault` TINYINT NOT NULL DEFAULT 0,
	`createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Category` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(200) NOT NULL,
	`createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Product` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`categoryId` INTEGER NOT NULL,
	`name` VARCHAR(300) NOT NULL,
	`slug` VARCHAR(300) NOT NULL,
	`basePrice` DECIMAL(15,2) NOT NULL,
	`material` VARCHAR(200) NOT NULL,
	`form` VARCHAR(100) NOT NULL COMMENT 'form dáng',
	`madeIn` VARCHAR(100) NOT NULL,
	`description` TEXT NOT NULL,
	`status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
	`createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `ProductVariant` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`productId` INTEGER NOT NULL,
	`color` VARCHAR(100) NOT NULL,
	`size` VARCHAR(20) NOT NULL,
	`sku` VARCHAR(100) NOT NULL,
	`stockQty` INTEGER NOT NULL DEFAULT 0,
	`createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `ProductImage` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`productId` INTEGER NOT NULL,
	`variantId` INTEGER NOT NULL,
	`imageUrl` VARCHAR(500) NOT NULL,
	`altText` VARCHAR(300) NOT NULL,
	`sortOrder` INTEGER NOT NULL DEFAULT 0,
	`isPrimary` TINYINT NOT NULL DEFAULT 0,
	`createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `InventoryTransaction` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`variantId` INTEGER NOT NULL,
	`orderId` INTEGER NOT NULL,
	`quantityChanged` INTEGER NOT NULL,
	`transactionType` VARCHAR(30) NOT NULL,
	`reason` VARCHAR(300) NOT NULL,
	`createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `BulkPricing` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`productId` INTEGER NOT NULL,
	`minQty` INTEGER NOT NULL,
	`discountPercent` DECIMAL(5,2) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `PrintPosition` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) NOT NULL,
	`extraCost` DECIMAL(15,2) NOT NULL DEFAULT 0,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Sticker` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(200) NOT NULL,
	`category` VARCHAR(100) NOT NULL,
	`imageUrl` VARCHAR(500) NOT NULL,
	`sortOrder` INTEGER NOT NULL DEFAULT 0,
	`isActive` TINYINT NOT NULL DEFAULT 1,
	`createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `CustomDesign` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`userId` INTEGER NOT NULL,
	`productId` INTEGER NOT NULL,
	`baseColor` VARCHAR(20) NOT NULL,
	`canvasData` LONGTEXT NOT NULL,
	`previewUrl` VARCHAR(500) NOT NULL,
	`designFee` DECIMAL(15,2) NOT NULL DEFAULT 0,
	`status` VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
	`createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `DesignPrintPosition` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`designId` INTEGER NOT NULL,
	`printPositionId` INTEGER NOT NULL,
	`extraCost` DECIMAL(15,2) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Cart` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`userId` INTEGER NOT NULL,
	`createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `CartItem` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`cartId` INTEGER NOT NULL,
	`variantId` INTEGER NOT NULL,
	`designId` INTEGER NOT NULL,
	`quantity` INTEGER NOT NULL DEFAULT 1,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Promotion` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`code` VARCHAR(50) NOT NULL,
	`discountType` VARCHAR(20) NOT NULL,
	`discountValue` DECIMAL(15,2) NOT NULL,
	`minOrderAmount` DECIMAL(15,2) NOT NULL DEFAULT 0,
	`startDate` DATETIME NOT NULL,
	`endDate` DATETIME NOT NULL,
	`usageLimit` INTEGER NOT NULL,
	`usedCount` INTEGER NOT NULL DEFAULT 0,
	`status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `CustomerOrder` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`orderCode` VARCHAR(50) NOT NULL,
	`userId` INTEGER NOT NULL,
	`promotionId` INTEGER NOT NULL,
	`addressId` INTEGER NOT NULL,
	`subtotal` DECIMAL(15,2) NOT NULL,
	`discountAmount` DECIMAL(15,2) NOT NULL DEFAULT 0,
	`totalAmount` DECIMAL(15,2) NOT NULL,
	`status` VARCHAR(30) NOT NULL DEFAULT 'PENDING',
	`createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `OrderItem` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`orderId` INTEGER NOT NULL,
	`variantId` INTEGER NOT NULL,
	`designId` INTEGER NOT NULL,
	`quantity` INTEGER NOT NULL,
	`unitPrice` DECIMAL(15,2) NOT NULL,
	`designFee` DECIMAL(15,2) NOT NULL DEFAULT 0,
	`lineTotal` DECIMAL(15,2) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Payment` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`orderId` INTEGER NOT NULL,
	`amount` DECIMAL(15,2) NOT NULL,
	`paymentMethod` VARCHAR(30) NOT NULL,
	`paymentType` VARCHAR(20) NOT NULL,
	`status` VARCHAR(20) NOT NULL DEFAULT 'PENDING',
	`transactionId` VARCHAR(255) NOT NULL,
	`createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
);


ALTER TABLE `UserToken`
ADD FOREIGN KEY(`userId`) REFERENCES `Account`(`id`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `UserAddress`
ADD FOREIGN KEY(`userId`) REFERENCES `Account`(`id`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `Product`
ADD FOREIGN KEY(`categoryId`) REFERENCES `Category`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ProductVariant`
ADD FOREIGN KEY(`productId`) REFERENCES `Product`(`id`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `ProductImage`
ADD FOREIGN KEY(`productId`) REFERENCES `Product`(`id`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `ProductImage`
ADD FOREIGN KEY(`variantId`) REFERENCES `ProductVariant`(`id`)
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE `InventoryTransaction`
ADD FOREIGN KEY(`variantId`) REFERENCES `ProductVariant`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `BulkPricing`
ADD FOREIGN KEY(`productId`) REFERENCES `Product`(`id`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `CustomDesign`
ADD FOREIGN KEY(`userId`) REFERENCES `Account`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CustomDesign`
ADD FOREIGN KEY(`productId`) REFERENCES `Product`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `DesignPrintPosition`
ADD FOREIGN KEY(`designId`) REFERENCES `CustomDesign`(`id`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `DesignPrintPosition`
ADD FOREIGN KEY(`printPositionId`) REFERENCES `PrintPosition`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Cart`
ADD FOREIGN KEY(`userId`) REFERENCES `Account`(`id`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `CartItem`
ADD FOREIGN KEY(`cartId`) REFERENCES `Cart`(`id`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `CartItem`
ADD FOREIGN KEY(`variantId`) REFERENCES `ProductVariant`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CartItem`
ADD FOREIGN KEY(`designId`) REFERENCES `CustomDesign`(`id`)
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE `CustomerOrder`
ADD FOREIGN KEY(`userId`) REFERENCES `Account`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CustomerOrder`
ADD FOREIGN KEY(`promotionId`) REFERENCES `Promotion`(`id`)
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE `CustomerOrder`
ADD FOREIGN KEY(`addressId`) REFERENCES `UserAddress`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `OrderItem`
ADD FOREIGN KEY(`orderId`) REFERENCES `CustomerOrder`(`id`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `OrderItem`
ADD FOREIGN KEY(`variantId`) REFERENCES `ProductVariant`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `OrderItem`
ADD FOREIGN KEY(`designId`) REFERENCES `CustomDesign`(`id`)
ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE `Payment`
ADD FOREIGN KEY(`orderId`) REFERENCES `CustomerOrder`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `InventoryTransaction`
ADD FOREIGN KEY(`orderId`) REFERENCES `CustomerOrder`(`id`)
ON UPDATE NO ACTION ON DELETE SET NULL;